### ISSUE TITLE
Crash with Mopidy 2.0.0.5 and mopidy-tidal

### ISSUE THREAD

**Issue by ZenithDK** [mones88/mopidy-tidal#2]
I am using python-tidal with the "fix_lossy" patch, and just updated to latest mopidy version from GitHub.
When I try to browse my artists in Mopidy-Mobile, I get this backtrace:
```
INFO     2016-02-18 20:30:36,379 [7037:TidalBackend-8] mopidy_tidal.library
  Browsing uri tidal:my_artists
ERROR    2016-02-18 20:30:36,937 [7037:Core-9] mopidy.core.library
  TidalBackend backend caused an exception.
Traceback (most recent call last):
  File "/home/lasse/dev/mopidy/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/home/lasse/dev/mopidy/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/home/lasse/.virtualenvs/mopidy/local/lib/python2.7/site-packages/mopidy_tidal/library.py", line 60, in browse
    return ref_models_mappers.create_artists(session.user.favorites.artists())
  File "/home/lasse/dev/python-tidal/tidalapi/__init__.py", line 320, in artists
    return self._session._map_request(self._base_url + '/artists', ret='artists')
  File "/home/lasse/dev/python-tidal/tidalapi/__init__.py", line 190, in _map_request
    return list(map(parse, [item['item'] for item in items]))
  File "/home/lasse/dev/python-tidal/tidalapi/__init__.py", line 214, in _parse_artist
    return Artist(id=json_obj['id'], name=json_obj['name'], role=Role(json_obj['type']))
KeyError: u'type'

```

**Comment by mones88** [comment]
You were using an unsupported version of tidalapi (the master branch is broken!!).
I've forked that library and using the latest version of mopidy-tidal it should work.
Please give a try a let me know.

**Comment by ZenithDK** [comment]
This seems to work now, thanks!
You have renamed the fork to tidalapi4mopidy - that is important for pip users and others.
